---
title: "Nieruchomości w Polsce"
author: "Natalia Cebulska, Natalia Leżuchowska, Błażej Bojka, Kacper Karnath"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)

data <- read.csv(file = "apartments_pl_2024_06.csv")
data
```

#CZYSZCZENIE DANYCH
# załadowanie wymaganych bibliotek
install.packages("tidyverse")
install.packages("dplyr")
install.packages("editrules")
install.packages("VIM")
install.packages("deducorrect")
install.packages("ISLR")

library(tidyverse)
library(dplyr)
library(editrules)
library(VIM)
library(deducorrect)
library(ISLR)

#Wykrywanie braków danych

sum(complete.cases(data))
nrow(data[complete.cases(data), ])/nrow(data)*100

is.special <- function(x){if (is.numeric(x)) !is.finite(x) else is.na(x)}
sapply(data, is.special)

for (n in colnames(data)){
is.na(data[[n]]) <- is.special(data[[n]])
}
summary(data)


###BRAKUJĄCE OBSERWACJE 
install.packages("naniar")
library(naniar)
library(dplyr)

#Utworzenie tabeli podsumowującej braki w tabeli 
miss_var_summary(data)

#Duże braki są zauważalne w: floor, buildYear 

#Utworzenie tabel podsumowujących według poszczególnych kategori
data %>%
  group_by(floor) %>%
  miss_var_summary()
  head(5)
  
data %>%
  group_by(collegeDistance) %>%
  miss_var_summary() 
  head(5)
  
data %>%
  group_by(floorCount) %>%
  miss_var_summary()
  head(5)
  
data %>%
  group_by(buildYear) %>%
  miss_var_summary() %>%
  head(5)


#Tabela podsumowująca brakujące wartości według wiersza    
data %>%
  miss_case_table()

#Wizualizacjia brakujących danych 
vis_miss(data)

#Wizualizacjia brakujących zmiennych, według poszczególnych wierszy
gg_miss_fct(data, fct = floor)

gg_miss_fct(data, fct = collegeDistance)

gg_miss_fct(data, fct = floorCount)

gg_miss_fct(data, fct = buildYear)


#Wizualizacja jak często braki współwystępują między zmiennymi 

gg_miss_upset(data, 
              nsets = 3)
              
#najwięcej brakuje danych w 
library(VIM)
data <-hotdeck(data)


